language: node_js
node_js: 8

cache:
  directory:
    - node_modules

script:
  - npm run predeploy

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: ./build
    on:
      branch: master