language: node_js
node_js: 8

cache:
  directories:
  - node_modules

script:
  - npm run predeploy

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: ./build
    target_branch: master
    on:
      branch: development