language: node_js

node_js:
  - 16

before_deploy:
  - rm -rf build && npm run predeploy

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep_history: true
    local_dir: ./build
    target_branch: master
    on:
      branch: development
