language: node_js
node_js: 10

before_deploy:
  - rm -rf build && npm run predeploy

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: ./build
    target_branch: master
    on:
      branch: development
